### ISSUE TITLE
Support for OAuth v2

### ISSUE THREAD

**Issue by JSONLewis** [jamiemaguiredotnet/SocialOpinion-Public#15]
**Is your feature request related to a problem? Please describe.**
Hi Jamie, Great work on building Social Opinion! I have just cloned the latest version of Master and it looks like this currently only supports OAuth1.1.

**Describe the solution you'd like**
The option to choose what version to use (either 1.1 or 2) and then the system will build the appropriate headers

**Comment by JSONLewis** [comment]
On further investigation I can see that references to the Bearer authorization are in the code. I  will investigate further to see if this is an issue or if this is something that I have just mis-interpreted

**Comment by jamiemaguiredotnet** [comment]
Thanks for connecting and offering your time!

I need to get the Wiki or GitHub pages setup to make it easier for newcomers to get started.
